### PR TITLE
Updating input parsing

### PR DESCRIPTION
**Pull request by tabedzki**
**Summary**

This change _should_ bring the input parsing into line with Steve's suggestion from [here](https://github.com/lammps/lammps/pull/2947#issuecomment-956561963) (suggestion (b)). 

@apsantos  can you confirm whether or not these changes make sense? I've also included a *possibly* missing keyword for the grid_frequency.

### CODE REVIEW

**Comment by apsantos** [comment]
I think these lines
`   if (strcmp(arg[1], "yes") == 0) write_grid_flag = 1;
     else if (strcmp(arg[1], "no") == 0) write_grid_flag = 0;`
need to be removed, unless we want to have a yes/no option, but I think just having the command covers that boolean, and we can replace that if statement with the presumed affirmative:
`write_grid_flag = 1`

Edited: thanks for coping those.

**Review by tabedzki — COMMENTED** [review]
@apsantos I think I updated the indexing properly and reviewed it. If you have time, I'd appreciate a lookover.

**Comment by tabedzki** [comment]
Fixed the indexing. I didn't realize it would've multiply counted the `tild` keyword. Indexing should now be correct.

**Review by tabedzki — COMMENTED** [review]
This should work

**Pull request merged**
